language: node_js
node_js: node
env:
  - WEBPACK_VERSION="webpack@3.x"
  - WEBPACK_VERSION="webpack@4.x"
install:
  - npm install
script:
  - npm install $WEBPACK_VERSION
  - npm test # The pretest hook runs a build
before_deploy:
  - mv .gitignore-deploy .gitignore
deploy:
  provider: npm
  skip_cleanup: true
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    branch: deploy
    tags: true
    condition: $WEBPACK_VERSION = "webpack@4.x" # Only deploy once